name = "telegram-bot"
main = "index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "telebot"
database_id = "6f7efc7b-e163-4d11-a21e-6d6d8ff289db"
